### DISCUSSION TITLE
0.6.0-beta.1

### DISCUSSION THREAD

**Discussion by mdelobelle** [mdelobelle/metadatamenu#420] [Announcements]
New Fields types:
- JSON
- YAML (frontmatter only)
- Object (collection of fields) enabling nested fields in frontmatter
- Object List (list of collection of fields) enabling nested fields in frontmatter
- All fields can define a "Parent" in their setting among the Object or ObjectList fields defined for the fileclass (or globally in the settings)

example 1 : Object field
```yaml
---
address:                               # Object field
  street: avenue Foch          # Input field
  number: 40                        # Number field
  city: "[[Paris]]"                  # File field
---
```

example 2 : Object List field
```yaml
---
players:                                 # ObjectList field
  - name: Mathieu                # Input field 
    grade: begginer               # Select Field
  - name: Jules                     # Input field (the same definition as above)
    grade: advanced             # Select Field (the same definition as above)
---
```

example 3: Mixing ObjectList and Object
```yaml
---
players:                                 # ObjectList field
  - name: Mathieu                # Input field 
    grade: begginer               # Select Field
    address:                           # Object field
      street: avenue Foch      # Input field
      number: 40                    # Number field
      city: "[[Paris]]"              # File field
  - name: Jules                     # Input field (the same definition as above)
    grade: advanced             # Select Field (the same definition as above)
    address:                           # Object field (the same definition as above)
      street: av de la paix      # Input field (the same definition as above)
      number: 25                    # Number field (the same definition as above)
      city: "[[Paris]]"              # File field (the same definition as above)
---
```

Fileclass mapping:
- globally Exclude folders from fileClass mapping
- map a fileclass with folders in your vault (associate their path in the fileclass setting view)
- map a fileclass with bookmark groups in your vault (associate their path in the fileclass setting view)

Commands and Menus:
- removed the "per field" options in the menu
- added an "Index Metadata Menu fields" command to force-reindex in case some data is incosistent in the modals
- Two way to nagivate in the 

Indexing:
- new indexing mecanism - independent from dataview and obsidian
- new index status in the status bar showing a rotating icon when the plugin is indeing data (meaning some values could be not up to date until the indexing is finished)
- the index status shows if there are Formulas or Lookup that have changed in a note and that haven't been automatically updated (when autoupdate is set to false in their setting). click on the icon to update all formulas and lookups in this note
- the metadatmenu button is displayed in a specific color (--text-warning) if there are Formulas or Lookup that have changed in a note and that haven't been automatically updated (when autoupdate is set to false in their setting). click on the index status icon to update all at once or open the Note Fields Modal to update them one by one 

<hr /><em>This discussion was created from the release <a href='https://github.com/mdelobelle/metadatamenu/releases/tag/'>0.6.0-beta.1</a>.</em>
