### DISCUSSION TITLE
lookup for nested fields

### DISCUSSION THREAD

**Discussion by ArneNostitz** [mdelobelle/metadatamenu#679] [Q&A]
hi, im currently trying to get a lookup working, where the links are in a nested object list. 

how would i need to setup this lookup? thanks!

lookup: project-name

frontmatter:
project
  project-name:[[project1]]
  date
  whatever-key
  project-name:[[project2]]
  date
  whatever-key
  project-name:[[project3]]
  date
  whatever-key

**Comment by LynetteCullens** [comment]
Right now, my current frontmatter looks like this:
```
---
fileClass: Variables
mathLink: ${\color{red}a}\left[\pu{m//s2},\pu{cm//s2},\pu{ft//s2} \right]$
mathLink-blocks:
  AltNotation: 
  LinkedDimensions: <span class="center-align"><sup style="font-size:150%;"><span style="font-size:200%;">[</span><span class="frac"><sup>[[Length#^Dimensions]]</sup><span>/</span><sub>[[Time#^Dimensions]]<sup>2</sup></sub></span><span style="font-size:200%;">]</span></span></span>
  LinkedStaticDimensions: 
  MKS: ${\color{red}a}[\pu{m//s2}]$
  CGS: ${\color{red}a}[\pu{cm//s2}]$
  FPS: ${\color{red}a}[\pu{ft//s2}]$
  LinkedFormula: <span class="center-align"><sup style="font-size:150%;">[[Acceleration]] = <span class="frac"><sup>[[Force]]*[[Gravitational Constant]]</sup><span>/</span><sub>[[Mass]]</sub></span></span></span>
  LinkedFormula1: 
  LinkedFormula2: 
  LinkedFormula3: 
  LinkedFormula4: 
  LinkedFormula5: 
  GetLinks: ""
aliases: 
parent: |-
  - "[[Length#^Dimensions]]"
  - "[[Time#^Dimensions]]"
  - "[[Force]]"
  - "[[Gravitational Constant]]"
  - "[[Mass]]"
same: 
Type: Variable

---
```
This plugin wouldn't work for me, so I downloaded Metaedit and used their API Instead to automatically call my nested links into a parent frontmatter property.


```dataviewjs
const { update } = app.plugins.plugins["metaedit"].api;
const activeFile = app.workspace.getActiveFile();
const currentTitle = activeFile ? activeFile.basename : "";

// Define fieldsToCheck array as optional, and filter out any potential undefined elements
const fieldsToCheck = [
  "LinkedDimensions",
  "LinkedStaticDimensions",
  "LinkedFormula",
  "LinkedFormula1",
  "LinkedFormula2",
  "LinkedFormula3",
  "LinkedFormula4",
  "LinkedFormula5"
].filter(field => field);

let links = [];

// Check if fieldsToCheck is defined before iterating over it
if (fieldsToCheck) {
  fieldsToCheck.forEach(field => {
    // Use optional chaining to safely access nested properties
    const fieldContent = dv.current().file.frontmatter["mathLink-blocks"]?.[field];
    if (fieldContent) {
      const matches = fieldContent.match(/\[\[([^\]]+)\]\]/g);
      if (matches) links.push(...matches);
    }
  });
}

links = [...new Set(links)].filter(link => link !== '[[Variables]]');

// Filter out links that match the current file's title
links = links.filter(link => !link.includes(currentTitle));

// Format links for output
const formattedLinks = links.map(link => `- "${link}"`).join("\n");

// Update the GetLinks property in the document's frontmatter
const currentFrontmatter = dv.current().file.frontmatter;
currentFrontmatter.GetLinks = formattedLinks;

// Check if any of the specified fields exist before updating
if (fieldsToCheck && Object.keys(currentFrontmatter["mathLink-blocks"] || {}).some(field => fieldsToCheck.includes(field))) {
  await update('parent', formattedLinks, activeFile);
}
```
**If you just want a list, this works**
```dataviewjs
const fields = [
  "LinkedDimensions",
  "LinkedStaticDimensions",
  "LinkedFormula",
  "LinkedFormula1",
  "LinkedFormula2",
  "LinkedFormula3",
  "LinkedFormula4",
  "LinkedFormula5"
];

let links = [];

fields.forEach(field => {
  const content = dv.current().file.frontmatter["mathLink-blocks"][field];
  if (content) {
    const matches = content.match(/\[\[([^\]]+)\]\]/g);
    if (matches) links.push(...matches);
  }
});

links = [...new Set(links)].filter(link => link !== '[[Variables]]');
dv.span(links.map(link => `- "${link}"`).join("\n"));

```
