### DISCUSSION TITLE
nested yaml in frontmatter

### DISCUSSION THREAD

**Discussion by TouriM** [mdelobelle/metadatamenu#70] [Q&A] [answered]
In some of my notes (mainly tasks etc.) I use nested yaml:

```yaml
Task:
    status:
    due:
    start:
    prio:
```

But I wasn't able to define those fields. I tried it with `Task.status` and `Task/status`.
