### ISSUE TITLE
FR: Support for nested dot notation. 

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#200]
Like Dataview, support something like page.link.property in formulas and lookups.

**Comment by mdelobelle** [comment]
This shoudl already be the case. Do you have a full example of field that you would like to set with this syntax?

**Comment by ertugruluyar-github** [comment]
It does not showing nested fileds in manage fileds menu section even.

**Comment by maksim77** [comment]
There is my frontmatter:
```
---
tags: [journal]
RHR: 
weight: 
glucose: 
running:
  distance:
  duration:
  avg_pace:
  avg_hr:
  max_hr:
  workout_type: 
---
```
It would be great if using the plugin you could set a value for example for the nested `distance` field of the `running` section.
