### ISSUE TITLE
Table view rows go behind column titles

### ISSUE THREAD

**Issue by auratheenby** [mdelobelle/metadatamenu#276]
In the table view of a fileClass, the rows go behind the column titles when you scroll down, making them harder to read.
![20230202_150332](https://user-images.githubusercontent.com/45722265/216448996-2da8900c-1c7d-48cd-a2fb-bae2cb2614ec.png)
They should probably be cut off at the line under the text for a clean transition.

**Comment by mdelobelle** [comment]
Hi, i'm definitely not good enough with css to achieve this 😅.

I'm using this snippet to tackle this
```css
.dataview.table-view-table > thead > tr > th {
  background-color: var(--background-primary);
}
```
