### ISSUE TITLE
[enhancement] Allow icons to be at the beginning of the file title

### ISSUE THREAD

**Issue by Smitty010** [mdelobelle/metadatamenu#429]
It would be nice if there was an option to choose whether the icon appears at the beginning or the end of the filename.  When I list files using dataview, I often can't see the icon because the filename is too long

**Comment by AtlcatlQ** [comment]
there's a way you could do it using css. You simply have to replace the `after` pseudo-element, with the `before` pseudo-element in the style cheatsheet

```css
.data-link-icon[data-link-status]::before{
    content: attr(data-link-status)" ";
}
```

![image](https://github.com/mdelobelle/metadatamenu/assets/87624226/4afbc3ee-b034-4dcf-925d-24b9a6d74ce6)

All of them are links to file which status is the icon before the name!
