### ISSUE TITLE
0.7.7 breaks lookup field functionality

### ISSUE THREAD

**Issue by renekalff** [mdelobelle/metadatamenu#552]
Starting with 0.7.7, when using a lookup field type only the "List" output types are working, in all other cases "--auto--" is displayed. It seems that the newly introduced function doesn't account for rawValues which aren't an array for example when using one of the summarisation functions.

**Comment by mdelobelle** [comment]
could you paste the definition of your lookup field ?
(located in the frontmatter of the fileclass file, under fields)

**Comment by renekalff** [comment]
I’m AfK at the moment but I’m pretty sure the summarisation isn’t working at all no matter the input (for example count of results in lookup). Only the list of files output is working in the latest version. If you cannot replicate the issue I’ll post an example in a few days.

**Comment by renekalff** [comment]
Hi Mathieu,

I've setup a test vault with 2 classes, Project and Task. Task has one boolean field "Done" and a file field in which you can select the project. In de Project class I've create 2 lookup fields with the following definition:

```yaml
  - name: Tasks
    type: Lookup
    options:
      autoUpdate: false
      outputType: LinksList
      builtinSummarizingFunction: Count
      customListFunction: page.file.name
      customSummarizingFunction: return pages.length
      targetFieldName: Project
      dvQueryString: dv.pages().where(p => p.fileClass == "Task")
    path: ""
    id: 2nAJnd
  - name: TasksDone
    type: Lookup
    options:
      autoUpdate: false
      outputType: BuiltinSummarizing
      builtinSummarizingFunction: Count
      customListFunction: page.file.name
      customSummarizingFunction: return pages.length
      dvQueryString: dv.pages().where(p => p.fileClass == "Task")
      targetFieldName: Project
      summarizedFieldName: Done
```

The "Tasks" lookup shows the links to the tasks which reference the project.
The "TasksDone" lookup shows "--auto--" or Empty in the frontmatter.

In version 0.7.6 the "TasksDone" lookup shows the count of done tasks.
