### ISSUE TITLE
The time type seems to be changed back to a "date" in the last update

### ISSUE THREAD

**Issue by htmljenn** [mdelobelle/metadatamenu#605]
I use fields with the "time" type every day and ever since the last update, when I try to fill in a property with that field I'm told "value must be a valid date."

![image](https://github.com/mdelobelle/metadatamenu/assets/826377/5929d8b4-6b54-4c9c-8029-596292443b93)

When I checked the Fileclass fields settings, all my Time entries now say "undefined" in the options area. When I try to edit them, they have date information instead of the HH:mm of a time field. 

I can create new Time fields, but any ones that existed before seem munged. 

![image](https://github.com/mdelobelle/metadatamenu/assets/826377/976361cb-3695-44f6-907c-c45ecd3b2b54)

**Comment by mdelobelle** [comment]
Hi, can you paste here the frontmatter of your fileclass file please? (to check the settings of your startTime and endTime fields)

**Comment by htmljenn** [comment]
Here you go, I removed the non-Time fields. 

```
extends:
fields:
  - name: endTime
    type: Time
    options:
      timeFormat: HH:mm
    path: ""
    id: aOch6O
  - name: startTime
    type: Time
    options:
      timeFormat: HH:mm
    path: ""
    id: YidYWA
version: "2.11"
limit: 20
mapWithTag: false
icon: file-text
tagNames: 
filesPaths: 
bookmarksGroups: 
excludes: 
savedViews: []
favoriteView: 
fieldsOrder:
  - YidYWA
  - aOch6O
  - umxMjB
  - suKNUh
  - D9SVSf
  - 2pLDFf
  - qzTbwM
  - cgGG4n
```
