### ISSUE TITLE
Multis within ObjectLists will Only Allow One Instance

### ISSUE THREAD

**Issue by ChristinWhite** [mdelobelle/metadatamenu#637]
## Issue

I'm not sure if ObjectLists were designed to let people put properties directly under than them rather than having ObjectList > Object > Non-Object Properties but it does save a couple of clicks and keeps things a tad bit cleaner. 

This mostly works great except for an issue with using Multis directly nested in an ObjectList where you can define only a single instance, if you try to create a second instance of multi the first instance and any other associated properties are instantly deleted.

[This may be easier to just show](https://share.cleanshot.com/2sGrSM6N) (please forgive how slow it is, CleanShot seems to slow my machine to a crawl when recording after a recent update).

## Reproduction

1. Create a fileClass.
2. Add a ObjectList.
3. Add an Input under the ObjectList so we can at least give it a unique name.
4. Add a Multi under the ObjectList and give it a value or two.
5. Apply the fileClass to a note and use Metadata Menu to add some properties, create your first input field and give it a value like 'instance one', add a multi and give it a value.
6. Create another instance with another input value, add a Multi field.
7. Select a value for Multi and watch your new instance kill instance one. 

## Desired Function

I'd love to be able to have 

```yaml
ObjectList:
  - Property one: Instance one
    Property two: Value from <multi>
  - Property one: Instance two
    Property Two: value from <multi>
```

## Notes

I haven't tried every other property type but input, select, boolean and object do not seem to have a Highlander complex.

## Workaround

We can use ObjectList > Object > Multi:

```yaml
ObjectList:
  - Object[0]
      - Property one: Instance one <string>
          Property two: Value from <multi> 
  - Object[1]
      - Property one: Instance one <string>
          Property two: Value from <multi> 
```

## Environment

Obsidian: 1.5.11
Metadata Menu: 0.8.5
