### ISSUE TITLE
Editing Nested Fields in Dataviewjs is Broken

### ISSUE THREAD

**Issue by LynetteCullens** [mdelobelle/metadatamenu#675]
### Dataviewjs Table Code

```dataviewjs 
const {fieldModifier: f} = this.app.plugins.plugins["metadata-menu"].api; 
dv.table (["File", "mathLink", "AltNotation", "Dimensions", "LinkedDimensions", "StaticDimensions", "LinkedStaticDimensions", "MKS", "CGS", "FPS", "LinkedFormula"], 
	await Promise.all(dv.pages('"Glossary"').map(async p => [ 
		p.file.link,
		await f(dv, p, "mathLink"),
		await f(dv, p, "mathLink-blocks.AltNotation"), 
		await f(dv, p, "mathLink-blocks.Dimensions"),
		await f(dv, p, "mathLink-blocks.LinkedDimensions"), 
		await f(dv, p, "mathLink-blocks.StaticDimensions"),
		await f(dv, p, "mathLink-blocks.LinkedStaticDimensions"),
		await f(dv, p, "mathLink-blocks.MKS"),
		await f(dv, p, "mathLink-blocks.CGS"),
		await f(dv, p, "mathLink-blocks.FPS"),
		await f(dv, p, "mathLink-blocks.LinkedFormula"), 
		]) 
)) 
```
![Change The Table](https://github.com/mdelobelle/metadatamenu/assets/45722611/d0a51621-2e7b-4e2b-af01-234acd694b31)

**Comment by LynetteCullens** [comment]
#612 I guess these are related.

**Comment by LynetteCullens** [comment]
```
---
fields:
  - name: mathLink
    type: Formula
    options: {}
      autoUpdate: false
    path: ""
    id: ZWukl8
  - name: mathLink-blocks
    type: ObjectList
    options: {}
      displayTemplate: ""
      itemDisplayTemplate: ""
    path: ""
    id: VSe8dE
  - name: AltNotation
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: E4RiFT
  - name: Dimensions
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: GxsjIA
  - name: StaticDimensions
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: fIYGua
  - name: MKS
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: gSOKjZ
  - name: CGS
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: KSTSXF
  - name: FPS
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: GuqBpP
  - name: LinkedFormula
    type: Input
    options: {}
      template: ""
    path: VSe8dE
    id: GYVn0Y
  - name: aliases
    type: Input
    options: {}
    path: ""
    id: MdiXOn
  - name: parent
    type: MultiFile
    options: {}
    path: ""
    id: rZeQiR
  - name: same
    type: MultiFile
    options: {}
    path: ""
    id: iMJoQ9
  - name: Type
    type: Select
    options: {}
      sourceType: ValuesList
      valuesList:
        "1": Dimension
        "2": Variable
        "3": Math Operation
        "4": Vocabulary
        "5": Sub_Variable
    path: ""
    id: Nj7xby
version: "2.8"
limit: 20
mapWithTag: false
icon: book-text
tagNames: 
filesPaths:
  - Glossary
bookmarksGroups: 
excludes: 
extends: 
savedViews: []
favoriteView: 
fieldsOrder:
  - ZWukl8
  - VSe8dE
  - E4RiFT
  - GxsjIA
  - fIYGua
  - gSOKjZ
  - KSTSXF
  - GuqBpP
  - GYVn0Y
  - MdiXOn
  - rZeQiR
  - iMJoQ9
  - Nj7xby
---
```
