### ISSUE TITLE
Lookup customListFunction breaks render

### ISSUE THREAD

**Issue by snelling-a** [mdelobelle/metadatamenu#681]
Hello,

Firstly, thank you for this plugin. It's a really great idea and I'm finding it very useful.

I am have a little problem with Lookups though. in my `daily_notes` class, i have this Lookup:

```yaml
  - name: test
    type: Lookup
    options:
      autoUpdate: true
      dvQueryString: dv.pages('"art_culture/music/album_of_the_day"')
      targetFieldName: date
      outputType: LinksList
      builtinSummarizingFunction: Count
      summarizedFieldName: ""
      customListFunction: page.file.name
      customSummarizingFunction: return pages.length
    path: ""
```
and it works great 
![Screenshot 2024-05-20 at 11 45 13](https://github.com/mdelobelle/metadatamenu/assets/72226000/d113ebf9-5ff1-4b7f-971e-a7d5c9012c55)

however, i would really like to see the `page.title` instead of the full path

```yaml
  - name: test
    type: Lookup
    options:
      autoUpdate: true
      dvQueryString: dv.pages('"art_culture/music/album_of_the_day"')
      targetFieldName: date
      outputType: CustomList # change here
      builtinSummarizingFunction: Count
      summarizedFieldName: ""
      customListFunction: page.title # change here
      customSummarizingFunction: return pages.length
    path: ""
```
and now, in the note, i see: 

![Screenshot 2024-05-20 at 11 48 06](https://github.com/mdelobelle/metadatamenu/assets/72226000/ac718d80-9dcb-408c-9381-d313c37df453)

and on the options modal i see:

![Screenshot 2024-05-20 at 11 48 32](https://github.com/mdelobelle/metadatamenu/assets/72226000/14a9bb35-a09c-487f-bb49-57db0e48fbbe)

i have even tried just returning a string and it is the same result

```yaml
      customListFunction: "'test'"
```
