### ISSUE TITLE
File explorer icons not vertically centered

### ISSUE THREAD

**Issue by zedtools** [mdelobelle/metadatamenu#693]
The icons in the Obsidian file explorer are not vertically centered with the text of the file name – they are slightly higher than the text. This applies to the icon for the fileClass of a file, as well as the "+" icon to add a new fileClass.

Example showing the fileClass icon:

<img width="238" alt="image" src="https://github.com/mdelobelle/metadatamenu/assets/30283145/d451bc8f-1f44-4023-bfb0-c4d079c2d244">

I managed to align them with the custom CSS:

```css
div.tree-item-self div.fileClass-add-button,
div.tree-item-self a.fileclass-icon
{
        align-self: center;
        margin-top: -0.1em;
}
```

Any chance something like this could be added to the plugin?

**Comment by zedtools** [comment]
I noticed the icons in Dataview queries are also not aligned.

Here is the updated CSS I am using.

```css
/* The "+" icon on the "Class Files path" folder */
div.tree-item-self div.fileClass-add-button,
/* The fileClass icon on a file */
div.tree-item-self a.fileclass-icon
{
	align-self: center;
	margin-top: -0.1em;
}
/* The fileClass in a Dataview query */
table.dataview a.fileclass-icon
{
	vertical-align: middle;
	margin-top: -0.2em;
}
```
