### ISSUE TITLE
Meta Bind & Metadata Menu - Nested Objects

### ISSUE THREAD

**Issue by ararrocks** [mdelobelle/metadatamenu#698]
Im trying to get those two plugins working together but i only get it to break YAML horribly.

I use Meta Bind JSEngine to create Nested values in a table. 
these are the two different versions of the YAML thats being created:
```
---
fileClass: test
address-Metadata-objectList:
  - address:
      type: Home
      country: SomeCountry
      state: SomeState
      postcode: 123123
      street: SomeStreet1
      city: SomeCity
  - address:
      type: Other
      country: OtherCountry
      state: OtherState
      postcode: 123123
      street: OtherStreet1
      city: OtherCity
address-metabindJS:
  - type: Home
    street: Somestreet
    city: SomeCity
    state: SomeState
    postcode: "123123"
    country: SomeCountry
  - type: Other
    street: OtherStreet
    city: OtherCity
    state: OtherState
    postcode: "123123"
    country: OtherCountry
---
```

i do prefer the way Meta Bind is creating these items in the list, without the "parent"ObjectList

and my settings in this image: 
![SCR-20240625-lwnk](https://github.com/mdelobelle/metadatamenu/assets/171629355/8af32d39-b3c4-4ee6-8767-e0d7093bae92)

any idea how to get this working together?
please help :)
