### ISSUE TITLE
fields order doesn't work

### ISSUE THREAD

**Issue by eresdf** [mdelobelle/metadatamenu#731]
I organized the fields in Metadata menu in the preferred order, however when I insert them in frontmatter, they are inserted in different order:((( it's so incontinent

**Comment by Peptino** [comment]
I tested in with a new vault and just Metadata Menu installed. New Fileclass folder created with a first fileclass. 
I created some fields for this fileclass (some with input type, others with number or select type). I sorted the fields correctly in the "Fileclass fields" view. In the source mode view of this fileclass note, I see this correct order in the "fieldsOrder" field. 
If I create a new note with this fileclass, the order of fields in the frontmatter part is the same order as in the "fields" list in the fileclass note. The "fieldsOrder" has no influence.

This is the fileclass note:

```
---
fields:
  - name: A
    type: Input
    options: {}
    path: ""
    id: qfAkJb
  - name: B
    type: Input
    options: {}
    path: ""
    id: AnvnWO
  - name: C
    type: Input
    options: {}
    path: ""
    id: kNF8OI
  - name: D-number
    type: Number
    options: {}
    path: ""
    id: S319LQ
  - name: F
    type: Input
    options: {}
    path: ""
    id: WbUAhz
  - name: G
    type: Input
    options: {}
    path: ""
    id: PRuNab
  - name: E-select
    type: Select
    options:
      sourceType: ValuesList
      valuesList:
        "1": a
        "2": b
        "3": c
    path: ""
    id: 2dvWfs
  - name: H-number
    type: Number
    options: {}
    path: ""
    id: OCPcGB
  - name: J
    type: Input
    options: {}
    path: ""
    id: Dropup
version: "2.52"
limit: 20
mapWithTag: false
icon: package
tagNames: 
filesPaths: 
bookmarksGroups: 
excludes: 
extends: 
savedViews: []
favoriteView: 
fieldsOrder:
  - qfAkJb
  - AnvnWO
  - kNF8OI
  - S319LQ
  - 2dvWfs
  - WbUAhz
  - PRuNab
  - OCPcGB
  - Dropup
---
```

The order in the fields part is "A, B, C, D-number, F, G, E-select, H-number, J" - and this is exactly the order in the frontmatter part of a new note.

The fieldsOrder is: A, B, C, D-number, E-select, F, G, H-number, J.

Changing the order of fields in the "Fileclass fields" view changes the order in the "fieldsOrder" field, but has no other impact.

The work-around is to manually adjust the order in the fields part of the fileclass note.
