### ISSUE TITLE
How to improve appearance of fileClass field

### ISSUE THREAD

**Issue by muteboy** [mdelobelle/metadatamenu#752]
Hi,
Thanks for making this plugin, it's really useful. Is there a way to style or otherwise make the display of unusual fileClass properties look better?
I have a fileClass called "Abbreviations" which allows me to define what meanings an abbreviation has, and in what context each meaning is in. For example, "CM" means "Command Module" in NASA. but "Configuration Manager" in another context.
Here's the source of the fileClass:

```
---
fields:
  - name: contexts
    type: ObjectList
    options:
      displayTemplate: "{{itemsCount}} items"
      itemDisplayTemplate: "{{itemIndex}}: {{term}}, {{fileContexts}}"
    path: ""
    id: Y53zNz
  - name: term
    type: File
    options: {}
    path: Y53zNz
    id: YBJeaW
  - name: fileContexts
    type: MultiFile
    options: {}
    path: Y53zNz
    id: E6HPRS
(other stuff)
---
```

When an example of the fileClass is displayed, the property looks like this (slightly different from the source - I'm trying different fields):
![Image](https://github.com/user-attachments/assets/5802d6db-1431-49c4-8b39-9cfc2da3cde5)

I looked at the Dev console to see what the CSS classes might be, and found this:
```
<div class="metadata-property-value">
<span class="metadata-property-value-item mod-unknown">[{"term":"[[Test Reports]]","fileContext":"[[State Machines]]"}]</span>
</div>
```

Would it be possible to provide a CSS class for the property? Or is there a way to display them differently?
